### ISSUE TITLE
Defined terms showing up as key terms

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/fec-eregs#316]
A number of defined terms are being parsed as key terms. I'll capture examples in this issue. This is not an exhaustive list, although it hsould cover most of 6, 100, 101 and 102.

- [ ] At the bottom of https://beta.fec.gov/regulations/6-103/2016-annual-6 _Section 504_ has a `key-term` class instead of a `defined-term` class.
    
    ![image](https://cloud.githubusercontent.com/assets/2626258/20730120/ae418eae-b639-11e6-9f29-3d8e31a18289.png)

- [ ] All but the first term here: https://beta.fec.gov/regulations/100-2/2016-annual-100#100-2-c-4-ii
- [ ] Both terms here: https://beta.fec.gov/regulations/100-3/2016-annual-100#100-3
- [ ] _Affiliated committee_ here: https://beta.fec.gov/regulations/100-5/2016-annual-100#100-5-g
- [ ] _Subordinate committee of a State, district, or local committee_ here: https://beta.fec.gov/regulations/100-14/2016-annual-100#100-14
- [ ] _Exceptions. Federal election activity_ here: https://beta.fec.gov/regulations/100-24/2016-annual-100#100-24-c
- [ ] All the terms here: https://beta.fec.gov/regulations/100-33/2016-annual-100#100-33
- [ ] All the terms here: https://beta.fec.gov/regulations/100-54/2016-annual-100#100-54
- [ ] All the terms here: https://beta.fec.gov/regulations/100-72/2016-annual-100#100-72
- [ ] All the terms here: https://beta.fec.gov/regulations/100-79/2016-annual-100#100-79
- [ ] All the terms here: https://beta.fec.gov/regulations/100-82/2016-annual-100#100-82
- [ ] All the terms here: https://beta.fec.gov/regulations/100-83/2016-annual-100#100-83
- [ ] All the terms here: https://beta.fec.gov/regulations/100-87/2016-annual-100#100-87
- [ ] All the terms here: https://beta.fec.gov/regulations/100-89/2016-annual-100#100-89
- [ ] All the terms here: https://beta.fec.gov/regulations/100-93/2016-annual-100#100-93
- [ ] All the terms here: https://beta.fec.gov/regulations/100-94/2016-annual-100#100-94
- [ ] All the terms here: https://beta.fec.gov/regulations/100-131/2016-annual-100#100-131
- [ ] All the terms here: https://beta.fec.gov/regulations/100-134/2016-annual-100#100-134
- [ ] All the terms here: https://beta.fec.gov/regulations/100-139/2016-annual-100#100-139
- [ ] All the terms here: https://beta.fec.gov/regulations/100-142/2016-annual-100#100-142
- [ ] All the terms here: https://beta.fec.gov/regulations/100-152/2016-annual-100#100-152
- [ ] All the terms here: https://beta.fec.gov/regulations/100-155/2016-annual-100#100-155
- [ ] All the terms here: https://beta.fec.gov/regulations/101-1/2016-annual-101#101-1
- [ ] All the terms here: https://beta.fec.gov/regulations/102-1/2016-annual-102#102-1
- [ ] All the terms here: https://beta.fec.gov/regulations/102-2/2016-annual-102#102-2
- [ ] All the terms here: https://beta.fec.gov/regulations/102-5/2016-annual-102#102-5
- [ ] All the terms here: https://beta.fec.gov/regulations/102-6/2016-annual-102#102-6
- [ ] All the terms here: https://beta.fec.gov/regulations/102-17/2016-annual-102#102-17
